{
 "title": "Edge Device Metrics - Unified Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "SHOW TAG VALUES FROM \"system_metrics\" WITH KEY = \"device_id\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU: Overall - total cpu usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_metrics",
     "query": "SELECT last(\"cpu\") AS \"Used\", 100 - last(\"disk\") AS \"Free\" \nFROM \"system_metrics\"\nWHERE \"device_id\" = 'edge-4a47aae248a3'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device_id::tag", "operator": "=", "value": "edge-4a47aae248a3" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "Vishnus-Mac.local" },
      { "condition": "AND", "key": "cpu::field", "operator": "=", "value": "select tag value" },
      { "condition": "AND", "key": "cpu::field", "operator": "=", "value": "select tag value" },
      { "condition": "AND", "key": "disk::field", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "CPU: Per Core - CPU by core",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "SELECT \n  mean(\"cpu_core_0\") AS \"core0\",\n  mean(\"cpu_core_1\") AS \"core1\",\n  mean(\"cpu_core_2\") AS \"core2\",\n  mean(\"cpu_core_3\") AS \"core3\",\n  mean(\"cpu_core_4\") AS \"core4\",\n  mean(\"cpu_core_5\") AS \"core5\",\n  mean(\"cpu_core_6\") AS \"core6\",\n  mean(\"cpu_core_7\") AS \"core7\"\nFROM \"system_metrics\"\nWHERE $timeFilter AND \"device_id\" =~ /.*/\nGROUP BY time($__interval), \"device_id\""
    }
   ]
  },
  {
   "title": "Memory - memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"memory_total\") AS \"total\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"memory_used\") AS \"used\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"memory_total\") - last(\"memory_used\") AS \"Free\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"memory_used\") / last(\"memory_total\") * 100 AS \"Used %\" FROM \"system_metrics\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Disk - Disk Usage metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"disk_total\") AS \"Disk Total\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"disk_used\") AS \"Disk Used\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"disk_total\") - last(\"disk_used\") AS \"Disk Free\" FROM \"system_metrics\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"disk_used\") / last(\"disk_total\") * 100 AS \"Disk Used %\" FROM \"system_metrics\" WHERE $timeFilter"
    }
   ]
  }
 ]
}